name:                in-other-words-plugin
version:             0.1.0.0
github:              "KingoftheHomeless/in-other-words-plugin"
license:             BSD3
author:              "Love Waern"
maintainer:          "combiner8761@gmail.com"
copyright:           "2020 Love Waern"
build-type:          Custom

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Disambiguate obvious uses of effects when using in-other-words.
category:            Control Language

description:         Please see the README on GitHub at <https://github.com/KingoftheHomeless/in-other-words-plugin#readme>

dependencies:
- base >= 4.9 && < 5
- ghc >= 8.4.4 && < 9
- ghc-tcplugins-extra >= 0.3 && < 0.5
- in-other-words >= 0.1 && < 0.3
- syb >= 0.7 && < 0.8
- transformers >= 0.5.2.0 && < 0.6
- containers >= 0.5 && < 0.7

custom-setup:
  dependencies:
    - base >= 4.9 && < 5
    - Cabal

library:
  source-dirs: src
  generated-other-modules:
  - Paths_in_other_words_plugin

tests:
  polysemy-plugin-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Control.Effect.Plugin
    build-tools:
    - hspec-discover
    dependencies:
    - in-other-words >= 0.1 && < 0.2
    - in-other-words-plugin
    - hspec >= 2.6.0 && < 3

default-extensions:
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - OverloadedStrings
  - TypeFamilies
